language: php

php:
  - 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate
  - php artisan make:crud Vehicle --bs3 --form-requests
  - php artisan make:crud-api Vehicle
  - php artisan make:crud-simple Vehicles/Type --parent=Vehicles --bs3
  - php artisan make:crud Product --formfield --bs3
  - php artisan make:crud-simple ProductType --formfield --bs3

script:
  - vendor/bin/phpunit
